version: "3.11"

services:

  app:
    build: .
    container_name: Plant_Ai

    ports:
      - "8501:8501"
    command: streamlit run genai.py --server.port 8501 --server.address 0.0.0.0
    volumes: 
      - .:/workspace  
    working_dir: /workspace
    restart: always
    environment:
      - TZ=Asia/Kolkata
      - PYTHONPATH=/workspace

  scheduler:
    build: .
    container_name: scheduler
    command: python alram.py
    volumes: 
      - .:/workspace  
    working_dir: /workspace
    restart: always
    environment:
      - TZ=Asia/Kolkata
      - PYTHONPATH=/workspace